### PR TITLE
Multi send link jan4

### PR DESCRIPTION
**Pull request by brentbagapuro**
New feature added as instructed on issue #560 : Facility: Send meeting link to different phone numbers and or emails

### CODE REVIEW

**Review by dccabs — CHANGES_REQUESTED** [review]
Putting in two phone numbers shows invalid phone number

Screen Shot 2023-01-09 at 8 39 13 PM

**Review by dccabs — CHANGES_REQUESTED** [review]
Adding two emails, when going to the next page only shows that it is sending to the first email in the input.

Screen Shot 2023-01-09 at 8 39 13 PM

Screen Shot 2023-01-09 at 8 40 06 PM

**Comment by dccabs** [comment]
Screen Shot 2023-01-09 at 8 43 11 PM

The text message is sending undefined.

**Comment by brentbagapuro** [comment]
@dccabs Just fixed the issues you mentioned. Basically it wasn't working because there was a whitespace in between emails and phones. I thought trim() would get rid of the whitespaces but turns out I should've used replace().

Also, I added a function to omit duplicate emails and phones.

**Review by dccabs — APPROVED** [review]
nice work brent!

**Pull request merged**
