### PR TITLE
Dependent edit remove sept20

### PR DESCRIPTION
**Pull request by lourdesyang1023**

### CODE REVIEW

**Review by dccabs — CHANGES_REQUESTED** [review]
When you delete a user, you get a success message, even when there is an error.


https://user-images.githubusercontent.com/558687/191568405-f4ee8fd8-bb87-40ab-b024-e7531cc925fb.mov

**Comment by lourdesyang1023** [comment]
> When you delete a user, you get a success message, even when there is an error. I'm unable to get the delete to work for either of the dependents on my account.
> 
>  Screen.Recording.2022-09-21.at.12.10.30.PM.mov

Thanks Dan for this. my bad i didn't handle it well. I push an update for fix on this.

**Review by dccabs — CHANGES_REQUESTED** [review]
This looks great Lourdes, one last request though.  When they hit the trash can icon to delete a dependent can you please pop open a modal that says "Are you sure you want to delete ${firstName} ${lastName} from your account?  This action can not be undone".  

Have a cancel button that closes the modal.  And a button that says "Delete".  When they hit delete then execute the endpoint.

**Comment by lourdesyang1023** [comment]
> This looks great Lourdes, one last request though. When they hit the trash can icon to delete a dependent can you please pop open a modal that says "Are you sure you want to delete firstName{lastName} from your account? This action can not be undone".
> 
> Have a cancel button that closes the modal. And a button that says "Delete". When they hit delete then execute the endpoint.

- pushed an update. Thank you Dan

**Review by dccabs — APPROVED** [review]
looks good

**Pull request merged**
