### PR TITLE
Feature/accout create page feb9

### PR DESCRIPTION
**Pull request by gr8fuljoe5**

### CODE REVIEW

**Comment by gr8fuljoe5** [comment]
Here's the URL:

http://localhost:3000/assisted-living/create-account

Screen Shot 2022-02-09 at 5 51 41 PM

**Comment by gr8fuljoe5** [comment]
URL: https://housecallmd-git-feature-accoutcreatepagefeb9-yucaba.vercel.app/assisted-living/create-account

**Review by dccabs — DISMISSED** [review]
looks good to me

**Review by dccabs — CHANGES_REQUESTED** [review]
There's a couple of more things in the ticket that need to be addressed.

*Call To Action Button - Create Account - should be disabled until all fields are properly filled out.

*Add Link under Call to action button - Already have an account? Login here. links to /login page

Please add the fullWidth attribute to the material components so they are wider on the screen.

Please add a little padding between the titile and the subtext.

Please use the hide/show password toggle like on this page

https://www.housecallmd.org/enter-login-information

**Comment by gr8fuljoe5** [comment]
Screen Shot 2022-02-11 at 4 21 00 PM

**Pull request merged**
